### ISSUE TITLE
Robot does not appear in RViz

### ISSUE THREAD

**Issue by danzimmerman** [danzimmerman/Universal_Robots_ROS2_Gazebo_Simulation#1]
There's no `.rviz` config file in this repo, so the file path constructed [here](https://github.com/danzimmerman/Universal_Robots_ROS2_Gazebo_Simulation/blob/dz/expose-joint-dyn-props/ur_simulation_gazebo/launch/ur_sim_control.launch.py#L67) is invalid.

**Comment by danzimmerman** [comment]
The above comment's issue is fixed but there are still problems with the MoveIt launch

**Comment by Icon45** [comment]
Hi @danzimmerman

don't know if this has something to do with the rviz config, but your repo also has the issue mentioned here: https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/issues/25

**Comment by Icon45** [comment]
> still problems with the MoveIt launch 

Are these problems fixed or is this repo merged into the official one from UR?

**Comment by danzimmerman** [comment]
Neither have happened yet, no.

I think that it's likely that it will be a while for some of these things to happen since it would make a lot more sense to build changes like this on top of some of the reorganization being considered for `ur_description`.

Keep in mind that the original UR Gazebo Simulation repo has not been officially released, so I don't imagine it will be a top priority for UR maintainers at the moment. 

You might try the UR Ignition Simulation package to see if that's working.

I'm working on this as a user who wanted to get Gazebo up and running and share my progress so far, but I have pretty limited time at present to work on it.

Will let you know if I get MoveIt fixed but it looked like a bit of a complicated change. Doable, but easier and cleaner if `ur_description` gets reorganized.

**Comment by Icon45** [comment]
Yeah no worries about not fixing it on your own. I understand that the reorganisation is worth the wait. I just wondered if it's already working or not. I hope UR releases the package soon.

**Comment by danzimmerman** [comment]
Going to close this and open #5 to track MoveIt separately.
